In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('../data/raw/neighborhood.csv')
df

,nbhd,P0020001,P0020005,P0020006,P0020002,P002aapi,P002others,P0040001,P0040005,P0040006,...,P0050005,P0050006,P0050007,P0050008,P0050009,P0050010,H0010001,H0010002,H0010003,hhsize
0,field concept,Total:,White alone,Black or African American alone,Hispanic or Latino,"Asian, Native Hawaiian and Pacific Islander al...","Other Races or Multiple Races, all ages",Total:,White alone,Black or African American alone,...,Nursing facilities/Skilled-nursing facilities,Other institutional facilities,Noninstitutionalized population:,College/University student housing,Military quarters,Other noninstitutional facilities,Total:,Occupied,Vacant,household size
1,Allston,28621,14634,1451,3657,7173,1706,26668,14022,1294,...,26,0,3364,3214,0,150,12527,11740,787,2.149148211
2,Back Bay,19588,14056,718,1326,2604,884,18374,13296,669,...,269,0,1701,1578,0,123,12373,10788,1585,1.633110864
3,Beacon Hill,9336,7521,252,537,630,396,8603,6980,231,...,0,0,33,0,0,33,6037,5485,552,1.696080219
4,Brighton,48330,30596,2289,4978,7801,2666,44129,28706,1966,...,240,56,3713,3493,0,220,21874,20822,1052,2.1279416
5,Charlestown,19120,13626,990,2075,1650,779,15661,11689,662,...,55,0,55,0,30,25,9525,8932,593,2.128302732
6,Chinatown,7143,1898,297,477,4281,190,6343,1790,254,...,224,0,457,443,0,14,3644,3299,345,1.958775386
7,Dorchester,122191,27411,42714,25285,13360,13421,95365,24327,32678,...,291,0,936,0,0,936,47965,44823,3142,2.692323138
8,Downtown,13451,9174,537,961,2286,493,12675,8764,529,...,97,0,4116,3283,0,833,6654,5401,1253,1.710423996
9,East Boston,43066,15760,1403,21700,1932,2271,34826,14039,1136,...,132,0,109,0,0,109,18016,16695,1321,2.564420485
10,Fenway,37733,20456,2396,3643,9218,2020,36715,20099,2281,...,261,0,16406,16197,0,209,13968,12661,1307,1.659663534
11,Hyde Park,33009,7449,15171,7901,677,1811,26470,6494,12229,...,67,0,134,64,0,70,12613,12066,547,2.719045251
12,Jamaica Plain,41012,22032,4686,8921,2985,2388,34817,19642,3848,...,319,120,529,160,0,369,18891,17724,1167,2.25423155
13,Longwood,4096,2573,334,381,657,151,3977,2555,304,...,0,0,3296,3296,0,0,456,425,31,1.882352941
14,Mattapan,23834,1489,16277,4079,490,1499,18511,1332,12951,...,85,0,102,0,0,102,9346,8821,525,2.66250992
15,Mission Hill,17886,6950,2469,3397,4228,842,15983,6661,1984,...,112,0,1667,1502,0,165,7139,6820,319,2.361143695
16,North End,10805,9306,141,528,445,385,10236,8888,132,...,41,0,148,0,116,32,6832,6314,518,1.681343047
17,Roslindale,29386,13428,6045,7373,1018,1522,23604,11486,4740,...,438,0,57,0,0,57,12114,11534,580,2.504074909
18,Roxbury,54905,7182,22796,16728,3277,4922,43502,6661,18023,...,0,41,3622,2520,0,1102,22034,20345,1689,2.474318014
19,South Boston,37917,29139,1529,3887,2077,1285,33614,26930,1084,...,188,0,125,0,0,125,19140,17961,1179,2.090529481
20,South Boston Waterfront,5579,4315,160,316,482,306,5286,4171,138,...,0,0,1,0,0,1,4622,3624,998,1.539183223
21,South End,29373,16618,2959,3783,4677,1336,25922,15203,2454,...,0,45,661,0,0,661,16619,15253,1366,1.879433554
22,West End,7705,4933,338,613,1440,381,7098,4620,303,...,0,57,53,0,0,53,5243,4572,671,1.65376203
23,West Roxbury,31561,20918,3312,3567,2451,1313,25457,17676,2399,...,412,0,93,0,0,93,14070,13390,680,2.319342793

In [23]:
# Set column names to the first row values
df.columns = df.iloc[0]
df = df.drop(df.index[0])
df

,field concept,Total:,White alone,Black or African American alone,Hispanic or Latino,"Asian, Native Hawaiian and Pacific Islander alone, all ages","Other Races or Multiple Races, all ages",Total:,White alone,Black or African American alone,...,Nursing facilities/Skilled-nursing facilities,Other institutional facilities,Noninstitutionalized population:,College/University student housing,Military quarters,Other noninstitutional facilities,Total:,Occupied,Vacant,household size
1,Allston,28621,14634,1451,3657,7173,1706,26668,14022,1294,...,26,0,3364,3214,0,150,12527,11740,787,2.149148211
2,Back Bay,19588,14056,718,1326,2604,884,18374,13296,669,...,269,0,1701,1578,0,123,12373,10788,1585,1.633110864
3,Beacon Hill,9336,7521,252,537,630,396,8603,6980,231,...,0,0,33,0,0,33,6037,5485,552,1.696080219
4,Brighton,48330,30596,2289,4978,7801,2666,44129,28706,1966,...,240,56,3713,3493,0,220,21874,20822,1052,2.1279416
5,Charlestown,19120,13626,990,2075,1650,779,15661,11689,662,...,55,0,55,0,30,25,9525,8932,593,2.128302732
6,Chinatown,7143,1898,297,477,4281,190,6343,1790,254,...,224,0,457,443,0,14,3644,3299,345,1.958775386
7,Dorchester,122191,27411,42714,25285,13360,13421,95365,24327,32678,...,291,0,936,0,0,936,47965,44823,3142,2.692323138
8,Downtown,13451,9174,537,961,2286,493,12675,8764,529,...,97,0,4116,3283,0,833,6654,5401,1253,1.710423996
9,East Boston,43066,15760,1403,21700,1932,2271,34826,14039,1136,...,132,0,109,0,0,109,18016,16695,1321,2.564420485
10,Fenway,37733,20456,2396,3643,9218,2020,36715,20099,2281,...,261,0,16406,16197,0,209,13968,12661,1307,1.659663534
11,Hyde Park,33009,7449,15171,7901,677,1811,26470,6494,12229,...,67,0,134,64,0,70,12613,12066,547,2.719045251
12,Jamaica Plain,41012,22032,4686,8921,2985,2388,34817,19642,3848,...,319,120,529,160,0,369,18891,17724,1167,2.25423155
13,Longwood,4096,2573,334,381,657,151,3977,2555,304,...,0,0,3296,3296,0,0,456,425,31,1.882352941
14,Mattapan,23834,1489,16277,4079,490,1499,18511,1332,12951,...,85,0,102,0,0,102,9346,8821,525,2.66250992
15,Mission Hill,17886,6950,2469,3397,4228,842,15983,6661,1984,...,112,0,1667,1502,0,165,7139,6820,319,2.361143695
16,North End,10805,9306,141,528,445,385,10236,8888,132,...,41,0,148,0,116,32,6832,6314,518,1.681343047
17,Roslindale,29386,13428,6045,7373,1018,1522,23604,11486,4740,...,438,0,57,0,0,57,12114,11534,580,2.504074909
18,Roxbury,54905,7182,22796,16728,3277,4922,43502,6661,18023,...,0,41,3622,2520,0,1102,22034,20345,1689,2.474318014
19,South Boston,37917,29139,1529,3887,2077,1285,33614,26930,1084,...,188,0,125,0,0,125,19140,17961,1179,2.090529481
20,South Boston Waterfront,5579,4315,160,316,482,306,5286,4171,138,...,0,0,1,0,0,1,4622,3624,998,1.539183223
21,South End,29373,16618,2959,3783,4677,1336,25922,15203,2454,...,0,45,661,0,0,661,16619,15253,1366,1.879433554
22,West End,7705,4933,338,613,1440,381,7098,4620,303,...,0,57,53,0,0,53,5243,4572,671,1.65376203
23,West Roxbury,31561,20918,3312,3567,2451,1313,25457,17676,2399,...,412,0,93,0,0,93,14070,13390,680,2.319342793

In [24]:
df.columns

Index(['field concept', 'Total:', 'White alone',
       'Black or African American alone', 'Hispanic or Latino',
       'Asian, Native Hawaiian and Pacific Islander alone, all ages',
       'Other Races or Multiple Races,  all ages', 'Total:', 'White alone',
       'Black or African American alone', 'Hispanic or Latino',
       'Asian, Native Hawaiian and Pacific Islander alone, aged 18+',
       'Other Races or Multiple Races, aged 18+', 'Total:, aged 0-17',
       'White alone, aged 0-17', 'Black or African American alone, aged 0-17',
       'Hispanic or Latino, aged 0-17',
       'Asian, Native Hawaiian and Pacific Islander alone, aged 0-17',
       'Other Races or Multiple Races, aged 0-17', 'household population',
       'Total:', 'Institutionalized population:',
       'Correctional facilities for adults', 'Juvenile facilities',
       'Nursing facilities/Skilled-nursing facilities',
       'Other institutional facilities', 'Noninstitutionalized population:',
       'College/University student housing', 'Military quarters',
       'Other noninstitutional facilities', 'Total:', 'Occupied', 'Vacant',
       'household size'],
      dtype='object', name=0)

In [25]:
# Rename columns
renames = {
    "field concept": "city",
    "White alone": "white",
    "Black or African American alone": "black",
    "Hispanic or Latino": "hispanic",
    "Asian, Native Hawaiian and Pacific Islander alone, all ages": "asian",
    "Other Races or Multiple Races,  all ages": "other",
    "household population": "household",
    "Institutionalized population:" : "institutionalized",
    "Correctional facilities for adults": "correctional",
    "Juvenile facilities": "juvenile",
    "Nursing facilities/Skilled-nursing facilities": "nursing",
    "Other institutional facilities": "other_institutional",
    "Noninstitutionalized population:" : "noninstitutionalized",
    "College/University student housing": "college",
    "Military quarters": "military",
    "Other noninstitutional facilities": "other_noninstitutional",
    "Occupied": "occupied",
    "Vacant": "vacant",
    "household size": "household_size",
}
df = df.rename(columns=renames)
df = df[renames.values()]
df

,city,white,white,black,black,hispanic,hispanic,asian,other,household,...,juvenile,nursing,other_institutional,noninstitutionalized,college,military,other_noninstitutional,occupied,vacant,household_size
1,Allston,14634,14022,1451,1294,3657,3071,7173,1706,25231,...,0,26,0,3364,3214,0,150,11740,787,2.149148211
2,Back Bay,14056,13296,718,669,1326,1205,2604,884,17618,...,0,269,0,1701,1578,0,123,10788,1585,1.633110864
3,Beacon Hill,7521,6980,252,231,537,475,630,396,9303,...,0,0,0,33,0,0,33,5485,552,1.696080219
4,Brighton,30596,28706,2289,1966,4978,4043,7801,2666,44308,...,13,240,56,3713,3493,0,220,20822,1052,2.1279416
5,Charlestown,13626,11689,990,662,2075,1387,1650,779,19010,...,0,55,0,55,0,30,25,8932,593,2.128302732
6,Chinatown,1898,1790,297,254,477,412,4281,190,6462,...,0,224,0,457,443,0,14,3299,345,1.958775386
7,Dorchester,27411,24327,42714,32678,25285,17390,13360,13421,120678,...,286,291,0,936,0,0,936,44823,3142,2.692323138
8,Downtown,9174,8764,537,529,961,877,2286,493,9238,...,0,97,0,4116,3283,0,833,5401,1253,1.710423996
9,East Boston,15760,14039,1403,1136,21700,16256,1932,2271,42813,...,12,132,0,109,0,0,109,16695,1321,2.564420485
10,Fenway,20456,20099,2396,2281,3643,3425,9218,2020,21013,...,0,261,0,16406,16197,0,209,12661,1307,1.659663534
11,Hyde Park,7449,6494,15171,12229,7901,5859,677,1811,32808,...,0,67,0,134,64,0,70,12066,547,2.719045251
12,Jamaica Plain,22032,19642,4686,3848,8921,6984,2985,2388,39954,...,90,319,120,529,160,0,369,17724,1167,2.25423155
13,Longwood,2573,2555,334,304,381,347,657,151,800,...,0,0,0,3296,3296,0,0,425,31,1.882352941
14,Mattapan,1489,1332,16277,12951,4079,2730,490,1499,23486,...,75,85,0,102,0,0,102,8821,525,2.66250992
15,Mission Hill,6950,6661,2469,1984,3397,2639,4228,842,16103,...,4,112,0,1667,1502,0,165,6820,319,2.361143695
16,North End,9306,8888,141,132,528,445,445,385,10616,...,0,41,0,148,0,116,32,6314,518,1.681343047
17,Roslindale,13428,11486,6045,4740,7373,5508,1018,1522,28882,...,9,438,0,57,0,0,57,11534,580,2.504074909
18,Roxbury,7182,6661,22796,18023,16728,12015,3277,4922,50340,...,160,0,41,3622,2520,0,1102,20345,1689,2.474318014
19,South Boston,29139,26930,1529,1084,3887,2799,2077,1285,37548,...,56,188,0,125,0,0,125,17961,1179,2.090529481
20,South Boston Waterfront,4315,4171,160,138,316,270,482,306,5578,...,0,0,0,1,0,0,1,3624,998,1.539183223
21,South End,16618,15203,2959,2454,3783,2993,4677,1336,28667,...,0,0,45,661,0,0,661,15253,1366,1.879433554
22,West End,4933,4620,338,303,613,531,1440,381,7561,...,0,0,57,53,0,0,53,4572,671,1.65376203
23,West Roxbury,20918,17676,3312,2399,3567,2546,2451,1313,31056,...,0,412,0,93,0,0,93,13390,680,2.319342793

In [26]:
df.to_csv('../data/clean/neighborhood.csv', index=False)